### ISSUE TITLE
Error when installing the mineral.

### ISSUE THREAD

**Issue by WayneML** [Zhoues/minerl-apptainer#1]
|diff -u1 -rN MCP-Reborn-vanilla/src/main/java/net/minecraft/world/server/ServerChunkProvider.java MCP-Reborn/src/main/java/net/minecraft/world/server/ServerChunkProvider.java
      |--- MCP-Reborn-vanilla/src/main/java/net/minecraft/world/server/ServerChunkProvider.java   2022-06-23 00:30:26.691515959 +0100
      |+++ MCP-Reborn/src/main/java/net/minecraft/world/server/ServerChunkProvider.java   2022-06-23 00:28:27.361515359 +0100
      --------------------------
      File to patch:
      Skip this patch? [y]
      4 out of 4 hunks ignored
      The text leading up to this was:
      --------------------------
      |diff -u1 -rN MCP-Reborn-vanilla/src/main/java/net/minecraft/world/server/ServerWorld.java MCP-Reborn/src/main/java/net/minecraft/world/server/ServerWorld.java
      |--- MCP-Reborn-vanilla/src/main/java/net/minecraft/world/server/ServerWorld.java   2022-06-23 00:30:26.691515959 +0100
      |+++ MCP-Reborn/src/main/java/net/minecraft/world/server/ServerWorld.java   2022-06-23 00:28:27.361515359 +0100
      --------------------------
      File to patch:
      Skip this patch? [y]
      5 out of 5 hunks ignored
      The text leading up to this was:
      --------------------------
      |diff -u1 -rN MCP-Reborn-vanilla/src/main/java/net/minecraft/world/spawner/WanderingTraderSpawner.java MCP-Reborn/src/main/java/net/minecraft/world/spawner/WanderingTraderSpawner.java
      |--- MCP-Reborn-vanilla/src/main/java/net/minecraft/world/spawner/WanderingTraderSpawner.java       2022-06-23 00:30:26.691515959 +0100
      |+++ MCP-Reborn/src/main/java/net/minecraft/world/spawner/WanderingTraderSpawner.java       2022-06-23 00:28:27.361515359 +0100
      --------------------------
      File to patch:
      Skip this patch? [y]
      1 out of 1 hunk ignored
      The text leading up to this was:
      --------------------------
      |diff -u1 -rN MCP-Reborn-vanilla/src/main/java/net/minecraft/world/spawner/WorldEntitySpawner.java MCP-Reborn/src/main/java/net/minecraft/world/spawner/WorldEntitySpawner.java
      |--- MCP-Reborn-vanilla/src/main/java/net/minecraft/world/spawner/WorldEntitySpawner.java   2022-06-23 00:30:26.691515959 +0100
      |+++ MCP-Reborn/src/main/java/net/minecraft/world/spawner/WorldEntitySpawner.java   2022-06-23 00:28:27.361515359 +0100
      --------------------------
      File to patch:
      Skip this patch? [y]
      12 out of 12 hunks ignored
      The text leading up to this was:
      --------------------------
      |diff -u1 -rN MCP-Reborn-vanilla/src/main/java/net/minecraft/world/storage/AnvilSaveConverter.java MCP-Reborn/src/main/java/net/minecraft/world/storage/AnvilSaveConverter.java
      |--- MCP-Reborn-vanilla/src/main/java/net/minecraft/world/storage/AnvilSaveConverter.java   2022-06-23 00:30:26.691515959 +0100
      |+++ MCP-Reborn/src/main/java/net/minecraft/world/storage/AnvilSaveConverter.java   2022-06-23 00:28:27.361515359 +0100
      --------------------------
      File to patch:
      Skip this patch? [y]
      2 out of 2 hunks ignored
      The text leading up to this was:
      --------------------------
      |diff -u1 -rN MCP-Reborn-vanilla/src/main/java/net/minecraft/world/storage/SaveFormat.java MCP-Reborn/src/main/java/net/minecraft/world/storage/SaveFormat.java
      |--- MCP-Reborn-vanilla/src/main/java/net/minecraft/world/storage/SaveFormat.java   2022-06-23 00:30:26.691515959 +0100
      |+++ MCP-Reborn/src/main/java/net/minecraft/world/storage/SaveFormat.java   2022-06-23 00:28:27.361515359 +0100
      --------------------------
      File to patch:
      Skip this patch? [y]
      6 out of 6 hunks ignored
      The next patch would create the file src/main/resources/index.txt,
      which already exists!  Assume -R? [n]
      Apply anyway? [n]
      1 out of 1 hunk ignored
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/zhz/z_jw/minerl/setup.py", line 222, in <module>
          prep_mcp()
        File "/home/zhz/z_jw/minerl/setup.py", line 198, in prep_mcp
          subprocess.check_call('{} downloadAssets'.format(gradlew).split(' '), cwd=workdir)
        File "/data/zhz_data/anaconda3/envs/MineDreamer/lib/python3.10/subprocess.py", line 364, in check_call
          retcode = call(*popenargs, **kwargs)
        File "/data/zhz_data/anaconda3/envs/MineDreamer/lib/python3.10/subprocess.py", line 345, in call
          with Popen(*popenargs, **kwargs) as p:
        File "/data/zhz_data/anaconda3/envs/MineDreamer/lib/python3.10/subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/data/zhz_data/anaconda3/envs/MineDreamer/lib/python3.10/subprocess.py", line 1863, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: '/home/zhz/z_jw/minerl/minerl/MCP-Reborn'
      
      
     I wonder if you have met this kind of error. I do not know how to solve it. Need help.

**Comment by Zhoues** [comment]
> ```
>   |diff -u1 -rN MCP-Reborn-vanilla/src/main/java/net/minecraft/world/server/ServerChunkProvider.java MCP-Reborn/src/main/java/net/minecraft/world/server/ServerChunkProvider.java
>   |--- MCP-Reborn-vanilla/src/main/java/net/minecraft/world/server/ServerChunkProvider.java   2022-06-23 00:30:26.691515959 +0100
>   |+++ MCP-Reborn/src/main/java/net/minecraft/world/server/ServerChunkProvider.java   2022-06-23 00:28:27.361515359 +0100
>   --------------------------
>   File to patch:
>   Skip this patch? [y]
>   4 out of 4 hunks ignored
>   The text leading up to this was:
>   --------------------------
>   |diff -u1 -rN MCP-Reborn-vanilla/src/main/java/net/minecraft/world/server/ServerWorld.java MCP-Reborn/src/main/java/net/minecraft/world/server/ServerWorld.java
>   |--- MCP-Reborn-vanilla/src/main/java/net/minecraft/world/server/ServerWorld.java   2022-06-23 00:30:26.691515959 +0100
>   |+++ MCP-Reborn/src/main/java/net/minecraft/world/server/ServerWorld.java   2022-06-23 00:28:27.361515359 +0100
>   --------------------------
>   File to patch:
>   Skip this patch? [y]
>   5 out of 5 hunks ignored
>   The text leading up to this was:
>   --------------------------
>   |diff -u1 -rN MCP-Reborn-vanilla/src/main/java/net/minecraft/world/spawner/WanderingTraderSpawner.java MCP-Reborn/src/main/java/net/minecraft/world/spawner/WanderingTraderSpawner.java
>   |--- MCP-Reborn-vanilla/src/main/java/net/minecraft/world/spawner/WanderingTraderSpawner.java       2022-06-23 00:30:26.691515959 +0100
>   |+++ MCP-Reborn/src/main/java/net/minecraft/world/spawner/WanderingTraderSpawner.java       2022-06-23 00:28:27.361515359 +0100
>   --------------------------
>   File to patch:
>   Skip this patch? [y]
>   1 out of 1 hunk ignored
>   The text leading up to this was:
>   --------------------------
>   |diff -u1 -rN MCP-Reborn-vanilla/src/main/java/net/minecraft/world/spawner/WorldEntitySpawner.java MCP-Reborn/src/main/java/net/minecraft/world/spawner/WorldEntitySpawner.java
>   |--- MCP-Reborn-vanilla/src/main/java/net/minecraft/world/spawner/WorldEntitySpawner.java   2022-06-23 00:30:26.691515959 +0100
>   |+++ MCP-Reborn/src/main/java/net/minecraft/world/spawner/WorldEntitySpawner.java   2022-06-23 00:28:27.361515359 +0100
>   --------------------------
>   File to patch:
>   Skip this patch? [y]
>   12 out of 12 hunks ignored
>   The text leading up to this was:
>   --------------------------
>   |diff -u1 -rN MCP-Reborn-vanilla/src/main/java/net/minecraft/world/storage/AnvilSaveConverter.java MCP-Reborn/src/main/java/net/minecraft/world/storage/AnvilSaveConverter.java
>   |--- MCP-Reborn-vanilla/src/main/java/net/minecraft/world/storage/AnvilSaveConverter.java   2022-06-23 00:30:26.691515959 +0100
>   |+++ MCP-Reborn/src/main/java/net/minecraft/world/storage/AnvilSaveConverter.java   2022-06-23 00:28:27.361515359 +0100
>   --------------------------
>   File to patch:
>   Skip this patch? [y]
>   2 out of 2 hunks ignored
>   The text leading up to this was:
>   --------------------------
>   |diff -u1 -rN MCP-Reborn-vanilla/src/main/java/net/minecraft/world/storage/SaveFormat.java MCP-Reborn/src/main/java/net/minecraft/world/storage/SaveFormat.java
>   |--- MCP-Reborn-vanilla/src/main/java/net/minecraft/world/storage/SaveFormat.java   2022-06-23 00:30:26.691515959 +0100
>   |+++ MCP-Reborn/src/main/java/net/minecraft/world/storage/SaveFormat.java   2022-06-23 00:28:27.361515359 +0100
>   --------------------------
>   File to patch:
>   Skip this patch? [y]
>   6 out of 6 hunks ignored
>   The next patch would create the file src/main/resources/index.txt,
>   which already exists!  Assume -R? [n]
>   Apply anyway? [n]
>   1 out of 1 hunk ignored
>   Traceback (most recent call last):
>     File "<string>", line 2, in <module>
>     File "<pip-setuptools-caller>", line 34, in <module>
>     File "/home/zhz/z_jw/minerl/setup.py", line 222, in <module>
>       prep_mcp()
>     File "/home/zhz/z_jw/minerl/setup.py", line 198, in prep_mcp
>       subprocess.check_call('{} downloadAssets'.format(gradlew).split(' '), cwd=workdir)
>     File "/data/zhz_data/anaconda3/envs/MineDreamer/lib/python3.10/subprocess.py", line 364, in check_call
>       retcode = call(*popenargs, **kwargs)
>     File "/data/zhz_data/anaconda3/envs/MineDreamer/lib/python3.10/subprocess.py", line 345, in call
>       with Popen(*popenargs, **kwargs) as p:
>     File "/data/zhz_data/anaconda3/envs/MineDreamer/lib/python3.10/subprocess.py", line 971, in __init__
>       self._execute_child(args, executable, preexec_fn, close_fds,
>     File "/data/zhz_data/anaconda3/envs/MineDreamer/lib/python3.10/subprocess.py", line 1863, in _execute_child
>       raise child_exception_type(errno_num, err_msg, err_filename)
>   FileNotFoundError: [Errno 2] No such file or directory: '/home/zhz/z_jw/minerl/minerl/MCP-Reborn'
>   
>   
>  I wonder if you have met this kind of error. I do not know how to solve it. Need help.
> ```

Hi, I haven't encountered this error before, the easiest way to install it is to use an already compiled `.whl` file, which is simple and without any problems.


![image](https://github.com/user-attachments/assets/1d2354d5-783d-4d4e-900d-d4ab4efe4f76)

**Comment by Zhoues** [comment]
@WayneML If the above method still doesn't work, you can check the official repository's [issues](https://github.com/minerllabs/minerl/issues) on MineRL to see if there are similar approaches suggested there.

Of course, we also offer pre-compiled containers, which you can choose to use to mitigate many issues. Additionally, if you encounter too many users facing this download error, you can consider providing alternative links for downloading.
```
curl http://43.159.131.178:8000/base-vgl-env.sif -O base-vgl-env.sif
```
